### PR TITLE
Update liquidity-container.tsx

### PR DESCRIPTION
**Pull request by rango527**

### CODE REVIEW

**Review by taariq — CHANGES_REQUESTED** [review]
You also removed the COMING SOON text and layout for the NANA pool as well as the centered Skip button and the removed Add liquidity button. Will you confirm those are back into the card?

**Comment by rango527** [comment]
https://github.com/VolumeFi/il-loss-charts/commit/21e49160137744ce971b2ab458ed51a2cab06bcb
This commit has no the removed codes you mentioned.

**Comment by taariq** [comment]
Check the unloaded diffs.

**Comment by rootedbox** [comment]
@rango527 you need to rebase this branch from banana-game

**Pull request closed without merging**
